# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80d783bb80244204a2022d92862df15975430581c35900d8391068a9abf6d0a85ad437660a9505c51e08faa1ac7a1c9d84696e946ceff77152a0e1dbfbe8778f

test:
  secret_key_base: 9db025e4a117b8e8435fa8e295221f426b40789efa2cd34c760cfb16639747e4bfb2caeafb8565b8dfffd1494e60922b98ea86aa5736042daa6271657da7c794

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
